---
roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.pip
    version: "3.0.1" # note that ranges are not supported for roles
  - name: geerlingguy.ansible
    version: "2.3.0" # note that ranges are not supported for roles
  - name: geerlingguy.java
    version: "2.3.2" # note that ranges are not supported for roles
  - name: geerlingguy.jenkins
    version: "5.1.0" # note that ranges are not supported for roles
  - name: googlecloudplatform.google_cloud_ops_agents
# collections:
